# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36b5c6147bc17f3159533fc9e97db02567bd4ba20ad107475fa56abc266e8166620d25ee6ad98ac9e42eff574c95256c28d6f58f4e4a6060a0ccc681520a096e

test:
  secret_key_base: e22782cf8a225760f9c73bfed8b333ec573beb2760166bd711d81ae328e1d8498f321b00c7d1a56361c63501f062465cb1d11d4c224d1e00f5f3bed99375aafd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
