require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AllegiancesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Allegiance. As you add validations to Allegiance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AllegiancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all allegiances as @allegiances" do
      allegiance = Allegiance.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:allegiances)).to eq([allegiance])
    end
  end

  describe "GET #show" do
    it "assigns the requested allegiance as @allegiance" do
      allegiance = Allegiance.create! valid_attributes
      get :show, {:id => allegiance.to_param}, valid_session
      expect(assigns(:allegiance)).to eq(allegiance)
    end
  end

  describe "GET #new" do
    it "assigns a new allegiance as @allegiance" do
      get :new, {}, valid_session
      expect(assigns(:allegiance)).to be_a_new(Allegiance)
    end
  end

  describe "GET #edit" do
    it "assigns the requested allegiance as @allegiance" do
      allegiance = Allegiance.create! valid_attributes
      get :edit, {:id => allegiance.to_param}, valid_session
      expect(assigns(:allegiance)).to eq(allegiance)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Allegiance" do
        expect {
          post :create, {:allegiance => valid_attributes}, valid_session
        }.to change(Allegiance, :count).by(1)
      end

      it "assigns a newly created allegiance as @allegiance" do
        post :create, {:allegiance => valid_attributes}, valid_session
        expect(assigns(:allegiance)).to be_a(Allegiance)
        expect(assigns(:allegiance)).to be_persisted
      end

      it "redirects to the created allegiance" do
        post :create, {:allegiance => valid_attributes}, valid_session
        expect(response).to redirect_to(Allegiance.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved allegiance as @allegiance" do
        post :create, {:allegiance => invalid_attributes}, valid_session
        expect(assigns(:allegiance)).to be_a_new(Allegiance)
      end

      it "re-renders the 'new' template" do
        post :create, {:allegiance => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested allegiance" do
        allegiance = Allegiance.create! valid_attributes
        put :update, {:id => allegiance.to_param, :allegiance => new_attributes}, valid_session
        allegiance.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested allegiance as @allegiance" do
        allegiance = Allegiance.create! valid_attributes
        put :update, {:id => allegiance.to_param, :allegiance => valid_attributes}, valid_session
        expect(assigns(:allegiance)).to eq(allegiance)
      end

      it "redirects to the allegiance" do
        allegiance = Allegiance.create! valid_attributes
        put :update, {:id => allegiance.to_param, :allegiance => valid_attributes}, valid_session
        expect(response).to redirect_to(allegiance)
      end
    end

    context "with invalid params" do
      it "assigns the allegiance as @allegiance" do
        allegiance = Allegiance.create! valid_attributes
        put :update, {:id => allegiance.to_param, :allegiance => invalid_attributes}, valid_session
        expect(assigns(:allegiance)).to eq(allegiance)
      end

      it "re-renders the 'edit' template" do
        allegiance = Allegiance.create! valid_attributes
        put :update, {:id => allegiance.to_param, :allegiance => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested allegiance" do
      allegiance = Allegiance.create! valid_attributes
      expect {
        delete :destroy, {:id => allegiance.to_param}, valid_session
      }.to change(Allegiance, :count).by(-1)
    end

    it "redirects to the allegiances list" do
      allegiance = Allegiance.create! valid_attributes
      delete :destroy, {:id => allegiance.to_param}, valid_session
      expect(response).to redirect_to(allegiances_url)
    end
  end

end
