require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RotCyphersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RotCypher. As you add validations to RotCypher, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RotCyphersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all rot_cyphers as @rot_cyphers" do
      rot_cypher = RotCypher.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rot_cyphers)).to eq([rot_cypher])
    end
  end

  describe "GET #show" do
    it "assigns the requested rot_cypher as @rot_cypher" do
      rot_cypher = RotCypher.create! valid_attributes
      get :show, {:id => rot_cypher.to_param}, valid_session
      expect(assigns(:rot_cypher)).to eq(rot_cypher)
    end
  end

  describe "GET #new" do
    it "assigns a new rot_cypher as @rot_cypher" do
      get :new, {}, valid_session
      expect(assigns(:rot_cypher)).to be_a_new(RotCypher)
    end
  end

  describe "GET #edit" do
    it "assigns the requested rot_cypher as @rot_cypher" do
      rot_cypher = RotCypher.create! valid_attributes
      get :edit, {:id => rot_cypher.to_param}, valid_session
      expect(assigns(:rot_cypher)).to eq(rot_cypher)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RotCypher" do
        expect {
          post :create, {:rot_cypher => valid_attributes}, valid_session
        }.to change(RotCypher, :count).by(1)
      end

      it "assigns a newly created rot_cypher as @rot_cypher" do
        post :create, {:rot_cypher => valid_attributes}, valid_session
        expect(assigns(:rot_cypher)).to be_a(RotCypher)
        expect(assigns(:rot_cypher)).to be_persisted
      end

      it "redirects to the created rot_cypher" do
        post :create, {:rot_cypher => valid_attributes}, valid_session
        expect(response).to redirect_to(RotCypher.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved rot_cypher as @rot_cypher" do
        post :create, {:rot_cypher => invalid_attributes}, valid_session
        expect(assigns(:rot_cypher)).to be_a_new(RotCypher)
      end

      it "re-renders the 'new' template" do
        post :create, {:rot_cypher => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rot_cypher" do
        rot_cypher = RotCypher.create! valid_attributes
        put :update, {:id => rot_cypher.to_param, :rot_cypher => new_attributes}, valid_session
        rot_cypher.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested rot_cypher as @rot_cypher" do
        rot_cypher = RotCypher.create! valid_attributes
        put :update, {:id => rot_cypher.to_param, :rot_cypher => valid_attributes}, valid_session
        expect(assigns(:rot_cypher)).to eq(rot_cypher)
      end

      it "redirects to the rot_cypher" do
        rot_cypher = RotCypher.create! valid_attributes
        put :update, {:id => rot_cypher.to_param, :rot_cypher => valid_attributes}, valid_session
        expect(response).to redirect_to(rot_cypher)
      end
    end

    context "with invalid params" do
      it "assigns the rot_cypher as @rot_cypher" do
        rot_cypher = RotCypher.create! valid_attributes
        put :update, {:id => rot_cypher.to_param, :rot_cypher => invalid_attributes}, valid_session
        expect(assigns(:rot_cypher)).to eq(rot_cypher)
      end

      it "re-renders the 'edit' template" do
        rot_cypher = RotCypher.create! valid_attributes
        put :update, {:id => rot_cypher.to_param, :rot_cypher => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested rot_cypher" do
      rot_cypher = RotCypher.create! valid_attributes
      expect {
        delete :destroy, {:id => rot_cypher.to_param}, valid_session
      }.to change(RotCypher, :count).by(-1)
    end

    it "redirects to the rot_cyphers list" do
      rot_cypher = RotCypher.create! valid_attributes
      delete :destroy, {:id => rot_cypher.to_param}, valid_session
      expect(response).to redirect_to(rot_cyphers_url)
    end
  end

end
