require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RunningKeysController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RunningKey. As you add validations to RunningKey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RunningKeysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all running_keys as @running_keys" do
      running_key = RunningKey.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:running_keys)).to eq([running_key])
    end
  end

  describe "GET #show" do
    it "assigns the requested running_key as @running_key" do
      running_key = RunningKey.create! valid_attributes
      get :show, {:id => running_key.to_param}, valid_session
      expect(assigns(:running_key)).to eq(running_key)
    end
  end

  describe "GET #new" do
    it "assigns a new running_key as @running_key" do
      get :new, {}, valid_session
      expect(assigns(:running_key)).to be_a_new(RunningKey)
    end
  end

  describe "GET #edit" do
    it "assigns the requested running_key as @running_key" do
      running_key = RunningKey.create! valid_attributes
      get :edit, {:id => running_key.to_param}, valid_session
      expect(assigns(:running_key)).to eq(running_key)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new RunningKey" do
        expect {
          post :create, {:running_key => valid_attributes}, valid_session
        }.to change(RunningKey, :count).by(1)
      end

      it "assigns a newly created running_key as @running_key" do
        post :create, {:running_key => valid_attributes}, valid_session
        expect(assigns(:running_key)).to be_a(RunningKey)
        expect(assigns(:running_key)).to be_persisted
      end

      it "redirects to the created running_key" do
        post :create, {:running_key => valid_attributes}, valid_session
        expect(response).to redirect_to(RunningKey.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved running_key as @running_key" do
        post :create, {:running_key => invalid_attributes}, valid_session
        expect(assigns(:running_key)).to be_a_new(RunningKey)
      end

      it "re-renders the 'new' template" do
        post :create, {:running_key => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested running_key" do
        running_key = RunningKey.create! valid_attributes
        put :update, {:id => running_key.to_param, :running_key => new_attributes}, valid_session
        running_key.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested running_key as @running_key" do
        running_key = RunningKey.create! valid_attributes
        put :update, {:id => running_key.to_param, :running_key => valid_attributes}, valid_session
        expect(assigns(:running_key)).to eq(running_key)
      end

      it "redirects to the running_key" do
        running_key = RunningKey.create! valid_attributes
        put :update, {:id => running_key.to_param, :running_key => valid_attributes}, valid_session
        expect(response).to redirect_to(running_key)
      end
    end

    context "with invalid params" do
      it "assigns the running_key as @running_key" do
        running_key = RunningKey.create! valid_attributes
        put :update, {:id => running_key.to_param, :running_key => invalid_attributes}, valid_session
        expect(assigns(:running_key)).to eq(running_key)
      end

      it "re-renders the 'edit' template" do
        running_key = RunningKey.create! valid_attributes
        put :update, {:id => running_key.to_param, :running_key => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested running_key" do
      running_key = RunningKey.create! valid_attributes
      expect {
        delete :destroy, {:id => running_key.to_param}, valid_session
      }.to change(RunningKey, :count).by(-1)
    end

    it "redirects to the running_keys list" do
      running_key = RunningKey.create! valid_attributes
      delete :destroy, {:id => running_key.to_param}, valid_session
      expect(response).to redirect_to(running_keys_url)
    end
  end

end
