require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SummonedCreaturesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SummonedCreature. As you add validations to SummonedCreature, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SummonedCreaturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all summoned_creatures as @summoned_creatures" do
      summoned_creature = SummonedCreature.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:summoned_creatures)).to eq([summoned_creature])
    end
  end

  describe "GET #show" do
    it "assigns the requested summoned_creature as @summoned_creature" do
      summoned_creature = SummonedCreature.create! valid_attributes
      get :show, {:id => summoned_creature.to_param}, valid_session
      expect(assigns(:summoned_creature)).to eq(summoned_creature)
    end
  end

  describe "GET #new" do
    it "assigns a new summoned_creature as @summoned_creature" do
      get :new, {}, valid_session
      expect(assigns(:summoned_creature)).to be_a_new(SummonedCreature)
    end
  end

  describe "GET #edit" do
    it "assigns the requested summoned_creature as @summoned_creature" do
      summoned_creature = SummonedCreature.create! valid_attributes
      get :edit, {:id => summoned_creature.to_param}, valid_session
      expect(assigns(:summoned_creature)).to eq(summoned_creature)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SummonedCreature" do
        expect {
          post :create, {:summoned_creature => valid_attributes}, valid_session
        }.to change(SummonedCreature, :count).by(1)
      end

      it "assigns a newly created summoned_creature as @summoned_creature" do
        post :create, {:summoned_creature => valid_attributes}, valid_session
        expect(assigns(:summoned_creature)).to be_a(SummonedCreature)
        expect(assigns(:summoned_creature)).to be_persisted
      end

      it "redirects to the created summoned_creature" do
        post :create, {:summoned_creature => valid_attributes}, valid_session
        expect(response).to redirect_to(SummonedCreature.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved summoned_creature as @summoned_creature" do
        post :create, {:summoned_creature => invalid_attributes}, valid_session
        expect(assigns(:summoned_creature)).to be_a_new(SummonedCreature)
      end

      it "re-renders the 'new' template" do
        post :create, {:summoned_creature => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested summoned_creature" do
        summoned_creature = SummonedCreature.create! valid_attributes
        put :update, {:id => summoned_creature.to_param, :summoned_creature => new_attributes}, valid_session
        summoned_creature.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested summoned_creature as @summoned_creature" do
        summoned_creature = SummonedCreature.create! valid_attributes
        put :update, {:id => summoned_creature.to_param, :summoned_creature => valid_attributes}, valid_session
        expect(assigns(:summoned_creature)).to eq(summoned_creature)
      end

      it "redirects to the summoned_creature" do
        summoned_creature = SummonedCreature.create! valid_attributes
        put :update, {:id => summoned_creature.to_param, :summoned_creature => valid_attributes}, valid_session
        expect(response).to redirect_to(summoned_creature)
      end
    end

    context "with invalid params" do
      it "assigns the summoned_creature as @summoned_creature" do
        summoned_creature = SummonedCreature.create! valid_attributes
        put :update, {:id => summoned_creature.to_param, :summoned_creature => invalid_attributes}, valid_session
        expect(assigns(:summoned_creature)).to eq(summoned_creature)
      end

      it "re-renders the 'edit' template" do
        summoned_creature = SummonedCreature.create! valid_attributes
        put :update, {:id => summoned_creature.to_param, :summoned_creature => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested summoned_creature" do
      summoned_creature = SummonedCreature.create! valid_attributes
      expect {
        delete :destroy, {:id => summoned_creature.to_param}, valid_session
      }.to change(SummonedCreature, :count).by(-1)
    end

    it "redirects to the summoned_creatures list" do
      summoned_creature = SummonedCreature.create! valid_attributes
      delete :destroy, {:id => summoned_creature.to_param}, valid_session
      expect(response).to redirect_to(summoned_creatures_url)
    end
  end

end
